[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "team09_cs107_2023"
version = "0.0.1"
authors = [
  { name="Hugo Nunez", email="hugonunez@college.harvard.edu" },
  { name="Zachary Stack", email="zstack@college.harvard.edu" },
  { name="Ricardo Linares", email="ricardolinares@college.harvard.edu" },
  { name="Sameer Das", email="sameerdas@college.harvard.edu" },
  { name="Paul Alexis", email="paulalexis@college.harvard.edu" }
]
description = "A spectral data analysis package for our client Victor Zhu for CS107"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Operating System :: OS Independent",
]
dependencies = [
   "astroquery>=0.4.4,<0.5",
  "astropy>=5.0,<5.1",
  "requests>=2.27,<3.0",
  "pandas>=1.4,<1.5",
  "scipy>=1.8,<1.9",
  "numpy>=1.22,<1.23",
  "matplotlib>=3.5,<3.6",
  "scikit-learn>=1.0,<1.1",
  "pytest>=7.1,<8.0"
]

[tool.hatch.build.targets.wheel]
# Define the packages or directories to include in the wheel package
packages = ["src"]

# will add more includes
files = ["README.md", "LICENSE"]

# Will exclude github eventually
exclude = []