[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "example_package_group8cs107"
version = "0.0.4"
authors = [
  { name="Hugo Nunez", email="hugonunez@college.harvard.edu" },
  { name="Zachary Stack", email="zstack@college.harvard.edu" },
  { name="Ricardo Linares", email="ricardolinares@college.harvard.edu" }
]
description = "A package to extract object information from Gaia dr3"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
   "matplotlib>=3.1",
    "pandas>=1.0",
    "astroquery>=0.4"
]

